### ISSUE TITLE
Add the posssibility to pass a redis client to the constructor

### ISSUE THREAD

**Issue by quentin-sommer** [dabroek/node-cache-manager-redis-store#7]
Hi,

I'm trying to use this library to implement dynamic cache objects that get re-allocated during the runtime. Because of this connections are leaking (clients are never `.quit()`).

Passing a Redis client in the constructor would allow me to create it on the module scope and guarantee that the same one is used during all the runtime. I don't think it would introduce any breaking changes in the library.

If you find this idea strange I've asked on the node_redis repo before and they also suggested using a top-level client https://github.com/NodeRedis/node_redis/issues/1338

I can open a PR if you're okay with this

Best

**Comment by dabroek** [comment]
Similar to what @stockholmux is saying it's a bit hard to understand what you require without any examples. It does feel like a very specific use case. As it says on the tin this package is trying to be as simple as possible. 

If you can create a simple and elegant PR showing what you are on about, you might be able to convince me to add it to the package.

**Comment by quentin-sommer** [comment]
@dabroek Thanks! Here's the PR:
https://github.com/dabroek/node-cache-manager-redis-store/pull/9

**Comment by quentin-sommer** [comment]
@dabroek Hi did you have a chance to take a look at the PR?

**Comment by quentin-sommer** [comment]
Closing as I'm not working on this anymore

**Comment by chescos** [comment]
I'd also be interested to see this getting merged.

**Comment by chrisspiegl** [comment]
Too bad @quentin-sommer stopped working on this and @dabroek has not looked into this?
Maybe it's worth taking a look again for all the reasons mentioned above.
I personally would like to attach a REDIS client via the constructor as well.
Main point being: REDIS is used for the Session store as well as some custom functionality and both of those are able to use one connection to the REDIS server, now it would be perfect if this module also would work the same way and be able to attach to that REDIS client too.

The package I use for sessions is called `connect-redis` and there they solved it by using the parameter `client` instead of `redisClient` but I guess that doesn't really matter much at the end.

The initialization would look like this (as far as I understand the PR that's already implemented):

```JS
const redisStore = require('cache-manager-redis-store')
const redis = require('redis')
const redisClient = redis.createClient({
  host: 'localhost', // default value
  port: 6379, // default value
  auth_pass: 'XXXXX',
  db: 0,
})
const redisCache = cacheManager.caching({
  store: redisStore,
  redisClient: redisClient,
  ttl: 600
})
```

I took a look at the PR and it looks really good and would love to see this merged (even though @quentin-sommer stopped working on it).
